### ISSUE TITLE
Not able to run modified example

### ISSUE THREAD

**Issue by mfazel** [RajLabMSSM/catalogueR#1]
#### I was trying to run the provided example from your catalogueR package in a modified way to optimize it for my query but it's failing. 
* If I use only the first file provided in the package (BST1_Nalls23andMe_2019_subset.tsv), it works, however if I remove extra columns other than the first 3 columns from the file, it fails with:
```Error : Problem with `mutate()` input `effect.is.ref`.```
I assumed only first 3 columns are necessary. 

* Trying with different "qtl_search" in the function fails in some cases. 
My guess is that data from different datasets can not be combined because they have different number of columns. The goal is to query all datasets for a few SNPs. I even tried a file with a single row of SNP, CHR, POS but after a while querying it crashed. Am I missing something?

* I also suggest adding the `sessionInfo()` output at the end of the provided example

Thsnks

**Comment by bschilder** [comment]
_(copying email correspondence from Sept 3rd 2020 for posterity)_

<hr>

**If I use only the first file provided in the package (BST1_Nalls23andMe_2019_subset.tsv), it works, however if I remove extra columns other than the first 3 columns from the file, it fails with:
`Error : Problem with `mutate()` input `effect.is.ref``.**
It's hard to say exactly why it's failing without knowing exactly what you did (a replicable script would be helpful if you could provide that), but two of the input data columns required are "A1" (the risk/effect allele in the GWAS being used as a query) and "A2" (the non-risk allele) which are used by the internal function `merge_gwas_qtl()` to create the columns effect.is.ref and effect.is.alt. So if A1 and A2 are missing from the query dataframe, it throws an error.
That said, I've modified the code so missing A1/A2 cols doesn't cause an issue and pushed the changes (effect.is.ref/effect.is.alt just won't be created).

**Also trying with different "qtl_search" in the function fails in some cases.** 
My guess is that data from different datasets can not be combined because they have different number of columns.
A reproducible example would also be helpful here. Having slightly different columns shouldn't be an issue since internally I always try to use `data.table::rbindlist(GWAS.QTL_all, fill = T) `when merging lists of dataframes (`fill=T` means it fills any missing cols with NAs). 

**My goal is to query all datasets for a few SNPs. I even tried a file with a single row of SNP, CHR, POS but after a while querying it crashed. What am I missing?**
Right now catalogueR is mainly oriented towards querying position ranges, as opposed to individual SNPs dispersed around the genome. However it is still possible to do this kind of querying with the internal function `catalogueR:::fetch_from_eqtl_cat_API()`. The downside is you'll have to manually construct the appropriate "link"  to get the SNPs you want. But eQTL Catalogue provides a tutorial here.
You could also just add a small range around each of your SNPs of interest (e.g. +/- 5bp) and then filter afterwards.
That said, trying to get SNPs are very specific positions, you might get a null result if that precise location isn't in the dataset you're querying (not all QTL datasets will contain all SNPs if they weren't included in the assay or if they were removed through filtering). 
Lastly, just double check that your query coordinates are in hg19 (or specify the `genome_build=` of your query in `eQTL_Catalogue.query()`).
I hope that helps!

**I also suggest adding the sessionInfo() output at the end of the provided example**
Definitely a good idea, will include that in the next update. Though the conda env should also help with dependency issues.

Best,
Brian
